version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: homie_postgres_dev
    environment:
      POSTGRES_DB: homie_db
      POSTGRES_USER: homie_user
      POSTGRES_PASSWORD: homie_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - homie_dev_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: homie_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - homie_dev_network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: homie_backend_dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://homie_user:homie_password@postgres:5432/homie_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret_key
      - JWT_EXPIRES_IN=1d
      - FAYDA_CLIENT_ID=crXYIYg2cJiNTaw5t-peoFzCRo-3JATNfBd5A8GU8tO
      - FAYDA_REDIRECT_URI=http://localhost:3000/callback
      - FAYDA_AUTHORIZATION_ENDPOINT=https://esignet.ida.fayda.et/authorize
      - FAYDA_TOKEN_ENDPOINT=https://esignet.ida.fayda.et/v1/esignet/oauth/v2/token
      - FAYDA_USERINFO_ENDPOINT=https://esignet.ida.fayda.et/v1/esignet/oidc/userinfo
      - FRONTEND_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "5000:5000"
      - "9229:9229" # Node.js debugging port
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    networks:
      - homie_dev_network
    command: npm run dev

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: homie_frontend_dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
      - NEXT_PUBLIC_FAYDA_CLIENT_ID=crXYIYg2cJiNTaw5t-peoFzCRo-3JATNfBd5A8GU8tO
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - homie_dev_network
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  homie_dev_network:
    driver: bridge